### ISSUE TITLE
Suggestion for Pypi information

### ISSUE THREAD

**Issue by HowcanoeWang** [cmpute/pcl.py#4]
It does an amazing job for Python point cloud analysis! You know that almost 90% of PCL python library depends on C++ PCL which is really really really difficult to install and hard to pack them in the product (GUI application etc.). Your library solved this problem, awesome!

I just missed this good library when I search in Pypi. I think it may be a good idea if you strengthen this is a **pure python** library **without C++ dependency** and **PCL library** in the Pypi introduction!

Thanks again for your great contribution! Hoping in the future, this library can include more useful funcions.

**Comment by cmpute** [comment]
I'm sorry that I have to change the library back to C++ implementation because there are tooooo many existing functions to reimplement! And I definitely won't have that much time to spend on this. I hope the cython wrapping will offer a smooth experience over existing C++ codes. 

In terms of PCL installation, it's easy to install both on Linux and Windows now. On linux you can just `sudo apt install libpcl` and on windows you can use `vcpkg`. If you have other installation requirements, I can offer python wheels.
